### PR TITLE
Windows Fixes + LLM old functions removal

### PR DESCRIPTION
**Pull request by samuelselleck**

### CODE REVIEW

**Comment by samuelselleck** [comment]
Don't merge this just yet - found another issue

**Comment by samuelselleck** [comment]
Should be ready to merge now! 👍

**Comment by samuelselleck** [comment]
One sec - need to verify template works

**Comment by samuelselleck** [comment]
Should be good now! :)

**Comment by warfaj** [comment]
don't merge, debugging a stickiness issue.

**Comment by warfaj** [comment]
nvm! can merge. 

We found a stickiness issue around the cartridge.tera files. Changes between them weren't being reflected between rebuilds when nothing else was changed. We narrowed it down to being due to macro caching. This is new post the .pax removal refactor because we now read the cartridge.partial.rs snippet at macro creation time which doesn't rerun if the macros dependencies don't change.

**Comment by zackbrown** [comment]
Thanks for tackling this, @samuelselleck !

**Pull request merged**
